# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "conda"
    directory: "/"
    schedule:
      interval: "daily"
      day: "monday"
      time: "06:00"
    commit-message:
      prefix: "[Dependabot-conda]"
    labels:
      - "dependabot"
    groups:
      netcdf:
        patterns:
          - "netcdf4"
          - "hdf5"
          - "h5py"

  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      day: "monday"
      time: "08:00"
    commit-message:
      prefix: "[Dependabot-pip]"
    labels:
      - "dependabot"
    groups:
      eccodes:
        patterns:
          - "eccodes"
          - "eccodeslib"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      # Check for updates to pre-commit hooks every week
      interval: "weekly"
