model: NEMO
exp: spinup-1990-nemo-dev
grid: eORCA12
description: 'FDB IFS/NEMO spinup with fractional sea ice coupling'
expver: a0cs
date: 19900101
data_start_date: '19900101'
data_end_date: '19911231'
fdb_path: /pfs/lustrep3/scratch/project_465000454/kaikeller/a0cs/config.yml
eccodes_path: /projappl/project_465000454/jvonhar/aqua/eccodes/eccodes-2.32.0/definitions
