#!/bin/bash
# --- EDIT THE SLURM DETAILS --- #  
# Set the partition 
# Set the computing account
# Set the machine
# ------------------------------ #

#SBATCH --job-name=aqua_container
#SBATCH --partition=compute
#SBATCH --account=bb1153
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=02:00:00
#SBATCH --error=aqua-container_%j.err
#SBATCH --output=aqua-container_%j.out
set -e

AQUA=$HOME/AQUA
machine=levante
version=latest

#----------------------------------------------#

bash $AQUA/cli/aqua-container/load-aqua-container.sh $machine -v $version <<EOF
#!/bin/bash
aqua --version
#--------------
EOF


###### Jupyter-lab in compute node for LUMI ######
# open aqua_slurm.err
# You will find an url like this: http://node_number:port_number/lab?token=random_value
# e.g. http://nid007521:8839/lab?token=random_value

# In a separate terminal run this :
# ssh -L port_number:node_number:port_number lumi_user@lumi.csc.fi (e.g.: ssh -L 8839:nid007521:8839 lumi_user@lumi.csc.fi)
# and open the URL in your browser, it will open jupyter-lab.

# If you face any issue, ask in the mattermost AQUA channel.