name: Conda Dependency Submission

on:
  workflow_dispatch: # Allows you to run it manually
  push:
    branches:
      - main
    paths:
      - 'environment.yml' # Trigger on changes to environment.yml

permissions:
  id-token: write
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Conda dependency scanning
        uses: advanced-security/conda-dependency-submission-action@v1.1.1
        with:
          treatAsPython: true